"""
AutoNet — Cascade Prompts & Pydantic Schema Definitions
========================================================
Defines the two structured output contracts for Qwen2.5-Coder-7B-Instruct:
  1. SectorCascadeAlert  — per-sector crisis diagnosis
  2. CityCascadeRollup   — city-wide multi-sector aggregation

All schemas use Pydantic v2 syntax. `model_json_schema()` output is passed
directly into llama-server's `response_format` field for GBNF grammar
enforcement — guaranteeing zero-hallucination, 100% valid JSON output.

Author  : AutoNet Systems Team
Runtime : Python 3.11+ | Pydantic v2
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — ENUMS
# ─────────────────────────────────────────────────────────────────────────────

class SectorSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH     = "HIGH"
    MEDIUM   = "MEDIUM"


class CityThreatLevel(str, Enum):
    RED    = "RED"
    ORANGE = "ORANGE"
    YELLOW = "YELLOW"


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — PYDANTIC OUTPUT MODELS
# ─────────────────────────────────────────────────────────────────────────────

class SectorCascadeAlert(BaseModel):
    """
    Structured LLM output for a single-sector cascade diagnosis.

    Generated by Qwen2.5 when a sector's healthScore drops below 35.
    Passed to the frontend via Socket.io `cascade-alert` event.
    """

    sector_id: str = Field(
        ...,
        description="The sectorId string for the affected sector (e.g. 'DEL_EAST_LN').",
    )
    severity: SectorSeverity = Field(
        ...,
        description="Assessed threat severity for this sector.",
    )
    root_causes: list[str] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="Concise list of identified root causes driving the anomaly.",
    )
    cascade_risk: str = Field(
        ...,
        description=(
            "Single sentence describing the downstream cascade risk if "
            "this sector is not mitigated — which adjacent sectors or "
            "domains are most vulnerable."
        ),
    )
    mitigation_actions: list[str] = Field(
        ...,
        min_length=1,
        max_length=5,
        description=(
            "Ordered list of concrete, agency-specific mitigation actions. "
            "Each must name a responsible agency (e.g. PWD, DTC, DISCOM)."
        ),
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Model's confidence in this diagnosis (0.0–1.0), "
            "based on signal clarity and historical pattern match."
        ),
    )


class CityCascadeRollup(BaseModel):
    """
    Structured LLM output for a city-wide multi-sector cascade aggregation.

    Generated by Qwen2.5 when ≥ 3 sectors are simultaneously alerting.
    Passed to the frontend via Socket.io `city-cascade` event.
    """

    incident_id: str = Field(
        ...,
        description=(
            "Unique incident identifier. Format: CITY_INCIDENT_YYYY_MMDD_NNN "
            "where NNN is a zero-padded sequence number."
        ),
    )
    affected_sectors: list[str] = Field(
        ...,
        description="List of sectorId strings contributing to this citywide cascade.",
    )
    city_threat_level: CityThreatLevel = Field(
        ...,
        description=(
            "Composite city-wide threat level. RED = immediate multi-district emergency, "
            "ORANGE = spreading cascade requiring coordinated response, "
            "YELLOW = elevated multi-sector watch."
        ),
    )
    executive_summary: str = Field(
        ...,
        description=(
            "2–3 sentence executive summary synthesizing all active alerts into "
            "a single coherent incident narrative for emergency coordinators."
        ),
    )
    coordinated_strategy: list[str] = Field(
        ...,
        min_length=2,
        max_length=6,
        description=(
            "Cross-agency coordinated response strategy. Each item must specify "
            "the action, the responsible agency, and the target sector or corridor."
        ),
    )
    estimated_resolution_mins: int = Field(
        ...,
        ge=5,
        le=1440,
        description=(
            "Estimated time to full resolution in minutes, "
            "based on severity, resource availability, and historical precedent."
        ),
    )


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — SCHEMA EXPORT HELPERS
# These return the exact dict to pass into llama-server's response_format.
# ─────────────────────────────────────────────────────────────────────────────

def sector_alert_response_format() -> dict[str, Any]:
    """
    Returns the response_format dict for llama-server GBNF enforcement
    of SectorCascadeAlert schema.

    Usage:
        response_format = sector_alert_response_format()
        # pass directly into openai client chat.completions.create()
    """
    return {
        "type"  : "json_object",
        "schema": SectorCascadeAlert.model_json_schema(),
    }


def city_rollup_response_format() -> dict[str, Any]:
    """
    Returns the response_format dict for llama-server GBNF enforcement
    of CityCascadeRollup schema.
    """
    return {
        "type"  : "json_object",
        "schema": CityCascadeRollup.model_json_schema(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — PROMPT BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

SECTOR_ALERT_SYSTEM_PROMPT = """\
You are AutoNet CascadeAI, an expert urban emergency analyst embedded in the \
Delhi Integrated Emergency Operations Centre.

Your task is to analyze real-time telemetry from a degraded city sector and \
produce a structured crisis assessment. You reason like a senior field coordinator \
with deep knowledge of Delhi's infrastructure interdependencies — drainage, \
power grid, road corridors, and DTC transit routes.

Rules:
- Be specific. Name actual Delhi locations, roads, agencies (PWD, MCD, DTC, DISCOM, NDRF).
- Root causes must be directly inferable from the telemetry — do not invent data.
- Mitigation actions must be actionable within 30 minutes by field teams.
- confidence_score reflects how clearly the telemetry supports your diagnosis.
- Respond ONLY with the JSON object. No preamble, no explanation, no markdown.\
"""


def build_sector_alert_prompt(
    sector_record_dict : dict[str, Any],
    history            : list[dict[str, Any]],
) -> str:
    """
    Builds the user-turn prompt for sector-level cascade diagnosis.

    Parameters
    ----------
    sector_record_dict : SectorRecord.to_dict() output
    history            : last N signal snapshots from SectorStateStore

    Returns
    -------
    str — formatted user prompt ready for chat completion
    """
    history_block = "\n".join([
        f"  [{i+1}] score={h.get('healthScore')} | "
        f"anomaly={h.get('anomalyLevel')} | "
        f"signal={h.get('signal', '')[:80]} | "
        f"ts={h.get('timestamp', '')}"
        for i, h in enumerate(history)
    ]) or "  No prior history available."

    return f"""\
SECTOR TELEMETRY REPORT
========================
Sector ID     : {sector_record_dict.get('sectorId')}
District      : {sector_record_dict.get('district')}
Domain        : {sector_record_dict.get('domain')}
Agent ID      : {sector_record_dict.get('agentId')}
Health Score  : {sector_record_dict.get('healthScore')} / 100
Anomaly Level : {sector_record_dict.get('anomalyLevel', '').upper()}
Metric Value  : {sector_record_dict.get('metricValue')}
Live Signal   : {sector_record_dict.get('signal')}
Location      : {sector_record_dict.get('location', {}).get('placeName', 'Unknown')}

SIGNAL HISTORY (most recent last):
{history_block}

Based on the above telemetry, produce a SectorCascadeAlert JSON assessment.
"""


CITY_ROLLUP_SYSTEM_PROMPT = """\
You are AutoNet CascadeAI operating at city-wide incident command level.

Multiple Delhi sectors are simultaneously in cascade alert. Your task is to \
synthesize all active sector alerts into a unified citywide incident assessment \
that emergency coordinators can act on immediately.

Rules:
- Identify the primary cascade chain — which sector failure triggered others.
- coordinated_strategy must assign specific agencies to specific sectors/corridors.
- executive_summary must read as an ops brief, not a description — actionable and precise.
- estimated_resolution_mins must be realistic given the severity and affected sectors.
- Respond ONLY with the JSON object. No preamble, no explanation, no markdown.\
"""


def build_city_rollup_prompt(
    active_alerts      : list[dict[str, Any]],
    sequence_number    : int = 1,
) -> str:
    """
    Builds the user-turn prompt for city-level cascade rollup.

    Parameters
    ----------
    active_alerts    : list of SectorRecord.to_dict() for all alerting sectors
    sequence_number  : incident sequence number for incident_id generation

    Returns
    -------
    str — formatted user prompt ready for chat completion
    """
    from datetime import datetime, timezone
    now      = datetime.now(timezone.utc)
    date_str = now.strftime("%Y_%m%d")
    seq_str  = str(sequence_number).zfill(3)

    alert_blocks = "\n\n".join([
        f"SECTOR {i+1}: {a.get('sectorId')} ({a.get('district')})\n"
        f"  Domain      : {a.get('domain')}\n"
        f"  Health Score: {a.get('healthScore')}\n"
        f"  Anomaly     : {a.get('anomalyLevel', '').upper()}\n"
        f"  Metric      : {a.get('metricValue')}\n"
        f"  Signal      : {a.get('signal')}\n"
        f"  Location    : {a.get('location', {}).get('placeName', 'Unknown')}\n"
        f"  Alerting For: {a.get('alertSince', 'unknown')}"
        for i, a in enumerate(active_alerts)
    ])

    return f"""\
CITYWIDE CASCADE INCIDENT REPORT
==================================
Timestamp        : {now.isoformat()}
Suggested ID     : CITY_INCIDENT_{date_str}_{seq_str}
Active Sectors   : {len(active_alerts)}
Sector IDs       : {[a.get('sectorId') for a in active_alerts]}

ACTIVE SECTOR ALERTS:
{alert_blocks}

Synthesize the above into a CityCascadeRollup JSON assessment for \
the Delhi Emergency Operations Centre.
"""