from typing import List
from config.sector_config import SectorConfig

ALL_SECTORS: List[SectorConfig] = [
    # ── Central Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_CENTRAL_CP",
        name="Connaught Place",
        district="Central Delhi",
        lat=28.6315,
        lng=77.2167,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=True,
        underpass_name="Minto Bridge Railway Underpass",
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Outer Circle & Minto Road Junction",
        baseline_bus_capacity=55,
        primary_corridor_name="Outer Circle & Minto Road Junction",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_CENTRAL_KB",
        recommended_bypass_route="Barakhamba Road via Deen Dayal Upadhyaya Marg",
        discom_provider="New Delhi Municipal Council (NDMC)",
        rated_substation_capacity_mw=250.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial & Financial District",
    ),
    SectorConfig(
        sector_id="DEL_CENTRAL_KB",
        name="Karol Bagh",
        district="Central Delhi",
        lat=28.6514,
        lng=77.1907,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.5,
        primary_choke_corridor="Ajmal Khan Road & Pusa Road Junction",
        baseline_bus_capacity=48,
        primary_corridor_name="Pusa Road Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_WEST_RG",
        recommended_bypass_route="Shankar Road via Ridge Road Circuit",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=180.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial Retail & Residential",
    ),
    SectorConfig(
        sector_id="DEL_CENTRAL_DG",
        name="Daryaganj",
        district="Central Delhi",
        lat=28.6459,
        lng=77.2410,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10111"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="Netaji Subhash Marg & Daryaganj Crossing",
        baseline_bus_capacity=42,
        primary_corridor_name="Netaji Subhash Marg",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_OLD_CHANDNI",
        recommended_bypass_route="Ringtone Bypass via Rajghat Marg",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=160.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial & Historical Heritage",
    ),

    # ── Central North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_CNORTH_MT",
        name="Model Town",
        district="Central North Delhi",
        lat=28.7115,
        lng=77.1913,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=True,
        underpass_name="Azadpur Railway Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.4,
        primary_choke_corridor="Model Town GT Road Junction",
        baseline_bus_capacity=38,
        primary_corridor_name="GT Karnal Road Corridor",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_NORTH_MN",
        recommended_bypass_route="Outer Ring Road Service Bypass",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=200.0,
        is_industrial_zone=False,
        industrial_zone_type="Residential & Transit Hub",
    ),
    SectorConfig(
        sector_id="DEL_CNORTH_SB",
        name="Shalimar Bagh",
        district="Central North Delhi",
        lat=28.7132,
        lng=77.1569,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10114"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.2,
        primary_choke_corridor="Shalimar Bagh Ring Road Crossing",
        baseline_bus_capacity=35,
        primary_corridor_name="North Ring Road Junction",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_NWEST_PTM",
        recommended_bypass_route="Inner Link Road via Wazirpur Industrial Area",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=190.0,
        is_industrial_zone=False,
        industrial_zone_type="Residential Zone",
    ),
    SectorConfig(
        sector_id="DEL_CNORTH_AV",
        name="Ashok Vihar",
        district="Central North Delhi",
        lat=28.6950,
        lng=77.1750,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=True,
        underpass_name="Satyawati Flyover Underbridge",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.3,
        primary_choke_corridor="Ashok Vihar Major Arterial Road",
        baseline_bus_capacity=32,
        primary_corridor_name="Satyawati Flyover Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_CNORTH_MT",
        recommended_bypass_route="Satyawati College Marg via Canal Road",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=175.0,
        is_industrial_zone=True,
        industrial_zone_type="Wazirpur Industrial & Steel Complex",
    ),

    # ── East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_EAST_LN",
        name="Laxmi Nagar",
        district="East Delhi",
        lat=28.6304,
        lng=77.2777,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=True,
        underpass_name="Vikas Marg Underpass",
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.6,
        primary_choke_corridor="Vikas Marg Transit Corridor",
        baseline_bus_capacity=60,
        primary_corridor_name="Vikas Marg Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_EAST_PV",
        recommended_bypass_route="Pushta Road via ITO Bridge Service Slip",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=210.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial High-Density Hub",
    ),
    SectorConfig(
        sector_id="DEL_EAST_MV",
        name="Mayur Vihar",
        district="East Delhi",
        lat=28.6096,
        lng=77.2905,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.1,
        primary_choke_corridor="Mayur Vihar Phase 1 Bus Corridor",
        baseline_bus_capacity=40,
        primary_corridor_name="Noida Link Road Corridor",
        free_flow_speed_kmh=60.0,
        upstream_sector_id="DEL_EAST_LN",
        recommended_bypass_route="DND Flyway Link via Akshardham Expressway",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=180.0,
        is_industrial_zone=False,
        industrial_zone_type="Suburban Residential Area",
    ),
    SectorConfig(
        sector_id="DEL_EAST_PV",
        name="Preet Vihar",
        district="East Delhi",
        lat=28.6389,
        lng=77.2953,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.5,
        primary_choke_corridor="Preet Vihar Vikas Marg Junction",
        baseline_bus_capacity=36,
        primary_corridor_name="Vikas Marg Extension",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_NEAST_DG",
        recommended_bypass_route="Karkardooma Court Complex Inner Circuit",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=170.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial & Institutional Zone",
    ),

    # ── New Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NEW_LUTYENS",
        name="Parliament / Lutyens",
        district="New Delhi",
        lat=28.6170,
        lng=77.2090,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=35.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.8,
        primary_choke_corridor="Central Secretariat Bus Terminal",
        baseline_bus_capacity=50,
        primary_corridor_name="Ashoka Road & Janpath Radial",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_CENTRAL_CP",
        recommended_bypass_route="Rafi Marg via Akbar Road Roundabout",
        discom_provider="New Delhi Municipal Council (NDMC)",
        rated_substation_capacity_mw=300.0,
        is_industrial_zone=False,
        industrial_zone_type="Government Administrative Zone",
    ),
    SectorConfig(
        sector_id="DEL_NEW_CHANAKYA",
        name="Chanakyapuri",
        district="New Delhi",
        lat=28.5933,
        lng=77.1900,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2556"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=35.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.6,
        primary_choke_corridor="Shanti Path Diplomatic Enclave",
        baseline_bus_capacity=25,
        primary_corridor_name="Shanti Path Corridor",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_NEW_LUTYENS",
        recommended_bypass_route="Niti Marg via Panchsheel Marg Loop",
        discom_provider="New Delhi Municipal Council (NDMC)",
        rated_substation_capacity_mw=220.0,
        is_industrial_zone=False,
        industrial_zone_type="Diplomatic Enclave",
    ),
    SectorConfig(
        sector_id="DEL_NEW_KHAN",
        name="Khan Market",
        district="New Delhi",
        lat=28.5992,
        lng=77.2265,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10111"},
        has_underpass=True,
        underpass_name="Golf Links / Subramaniam Bharti Marg Junction",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=1.8,
        primary_choke_corridor="Subramaniam Bharti Marg Junction",
        baseline_bus_capacity=30,
        primary_corridor_name="Subramaniam Bharti Marg",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_NEW_LUTYENS",
        recommended_bypass_route="Max Mueller Marg via Lodhi Road",
        discom_provider="New Delhi Municipal Council (NDMC)",
        rated_substation_capacity_mw=150.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial & High-End Retail",
    ),

    # ── North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NORTH_CL",
        name="Civil Lines",
        district="North Delhi",
        lat=28.6775,
        lng=77.2214,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10121"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.0,
        primary_choke_corridor="Civil Lines Boulevard Road",
        baseline_bus_capacity=30,
        primary_corridor_name="Rajpur Road Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_NORTH_KGATE",
        recommended_bypass_route="Sham Nath Marg via Ridge Road Bypass",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=160.0,
        is_industrial_zone=False,
        industrial_zone_type="Institutional & Heritage Residential",
    ),
    SectorConfig(
        sector_id="DEL_NORTH_MN",
        name="Mukherjee Nagar",
        district="North Delhi",
        lat=28.7050,
        lng=77.2100,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.1,
        primary_choke_corridor="Mukherjee Nagar Banda Bahadur Marg",
        baseline_bus_capacity=45,
        primary_corridor_name="Banda Bahadur Marg Corridor",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_CNORTH_MT",
        recommended_bypass_route="Ring Road via Kingsway Camp Circuit",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=180.0,
        is_industrial_zone=False,
        industrial_zone_type="Educational & High-Density Commercial",
    ),
    SectorConfig(
        sector_id="DEL_NORTH_KGATE",
        name="Kashmere Gate",
        district="North Delhi",
        lat=28.6665,
        lng=77.2290,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=True,
        underpass_name="ISBT Ring Road Boulevard Underpass",
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.7,
        primary_choke_corridor="ISBT Kashmere Gate Ring Road Corridor",
        baseline_bus_capacity=75,
        primary_corridor_name="ISBT Ring Road Boulevard",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_OLD_CHANDNI",
        recommended_bypass_route="Salimgarh Bypass via Geeta Colony Bridge",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=260.0,
        is_industrial_zone=False,
        industrial_zone_type="Major Inter-State Transit Terminal",
    ),

    # ── North East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NEAST_YV",
        name="Yamuna Vihar",
        district="North East Delhi",
        lat=28.6950,
        lng=77.2820,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10121"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.7,
        primary_choke_corridor="Yamuna Vihar Wazirabad Road",
        baseline_bus_capacity=38,
        primary_corridor_name="Wazirabad Road Highway Corridor",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_NEAST_SLP",
        recommended_bypass_route="Bhajjanpura Main Market Service Lane",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=175.0,
        is_industrial_zone=False,
        industrial_zone_type="Residential & Arterial Transit",
    ),
    SectorConfig(
        sector_id="DEL_NEAST_DG",
        name="Dilshad Garden",
        district="North East Delhi",
        lat=28.6800,
        lng=77.3210,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10118"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.3,
        primary_choke_corridor="Dilshad Garden GT Road Junction",
        baseline_bus_capacity=35,
        primary_corridor_name="GT Road Shahdara Corridor",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_EAST_PV",
        recommended_bypass_route="Vivek Vihar Underpass Corridor",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=185.0,
        is_industrial_zone=True,
        industrial_zone_type="Jhilmil Industrial Area",
    ),
    SectorConfig(
        sector_id="DEL_NEAST_SLP",
        name="Seelampur",
        district="North East Delhi",
        lat=28.6710,
        lng=77.2680,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10118"},
        has_underpass=True,
        underpass_name="Seelampur GT Road Underpass",
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.4,
        primary_choke_corridor="Seelampur GT Road Transit Corridor",
        baseline_bus_capacity=50,
        primary_corridor_name="Seelampur Flyover GT Road Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_NEAST_YV",
        recommended_bypass_route="Shastri Park Marginal Bandh Road",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=195.0,
        is_industrial_zone=False,
        industrial_zone_type="High-Density Mixed Commercial",
    ),

    # ── North West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NWEST_ROH",
        name="Rohini",
        district="North West Delhi",
        lat=28.7495,
        lng=77.0700,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11267"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.5,
        primary_choke_corridor="Rohini Sector 7 Outer Ring Road",
        baseline_bus_capacity=42,
        primary_corridor_name="Rohini Outer Ring Road Arterial",
        free_flow_speed_kmh=60.0,
        upstream_sector_id="DEL_NWEST_PTM",
        recommended_bypass_route="Sector 10 Inner Avenue Road",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=240.0,
        is_industrial_zone=False,
        industrial_zone_type="Suburban Commercial & Residential",
    ),
    SectorConfig(
        sector_id="DEL_NWEST_NGL",
        name="Nangloi",
        district="North West Delhi",
        lat=28.6830,
        lng=77.0640,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10708"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.0,
        primary_choke_corridor="Nangloi Rohtak Road Junction",
        baseline_bus_capacity=48,
        primary_corridor_name="Rohtak Road Highway Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_WEST_TILAK",
        recommended_bypass_route="Najafgarh-Nangloi Rural Feeder Road",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=200.0,
        is_industrial_zone=True,
        industrial_zone_type="Nangloi Small Scale Industrial Cluster",
    ),
    SectorConfig(
        sector_id="DEL_NWEST_PTM",
        name="Pitampura",
        district="North West Delhi",
        lat=28.6980,
        lng=77.1310,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10114"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.6,
        primary_choke_corridor="Pitampura TV Tower Junction",
        baseline_bus_capacity=40,
        primary_corridor_name="Madhuban Chowk Outer Ring Road",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_CNORTH_SB",
        recommended_bypass_route="Pitampura Ring Road Service Lanes",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=210.0,
        is_industrial_zone=False,
        industrial_zone_type="Residential & Commercial Hub",
    ),

    # ── Old Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_OLD_CHANDNI",
        name="Chandni Chowk",
        district="Old Delhi",
        lat=28.6506,
        lng=77.2303,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.9,
        primary_choke_corridor="Chandni Chowk Main Road",
        baseline_bus_capacity=28,
        primary_corridor_name="Netaji Subhash Marg Old Delhi",
        free_flow_speed_kmh=35.0,
        upstream_sector_id="DEL_OLD_SADAR",
        recommended_bypass_route="Ring Road via Red Fort Outer Bypass",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=140.0,
        is_industrial_zone=False,
        industrial_zone_type="Dense Commercial Wholesale District",
    ),
    SectorConfig(
        sector_id="DEL_OLD_SADAR",
        name="Sadar Bazar",
        district="Old Delhi",
        lat=28.6580,
        lng=77.2130,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Sadar Bazar Qutub Road Junction",
        baseline_bus_capacity=30,
        primary_corridor_name="Qutub Road Arterial",
        free_flow_speed_kmh=35.0,
        upstream_sector_id="DEL_OLD_CHAWRI",
        recommended_bypass_route="Rani Jhansi Flyover Expressway",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=130.0,
        is_industrial_zone=False,
        industrial_zone_type="Wholesale Trade & Logistics Cluster",
    ),
    SectorConfig(
        sector_id="DEL_OLD_CHAWRI",
        name="Chawri Bazar",
        district="Old Delhi",
        lat=28.6480,
        lng=77.2260,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Chawri Bazar Chowk",
        baseline_bus_capacity=20,
        primary_corridor_name="Asaf Ali Road Corridor",
        free_flow_speed_kmh=35.0,
        upstream_sector_id="DEL_CENTRAL_DG",
        recommended_bypass_route="JLN Marg via Delhi Gate Intersection",
        discom_provider="BSES Yamuna Power Limited (BYPL)",
        rated_substation_capacity_mw=120.0,
        is_industrial_zone=False,
        industrial_zone_type="High-Density Heritage Trade Area",
    ),

    # ── Outer North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_ONORTH_NARELA",
        name="Narela",
        district="Outer North Delhi",
        lat=28.8520,
        lng=77.0910,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10706"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.5,
        primary_choke_corridor="Narela Anaj Mandi Road",
        baseline_bus_capacity=25,
        primary_corridor_name="Narela Railway Road Highway",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_ONORTH_ALIPUR",
        recommended_bypass_route="Singhu Border Freight Bypass Expressway",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=220.0,
        is_industrial_zone=True,
        industrial_zone_type="Narela Industrial & Food Processing Park",
    ),
    SectorConfig(
        sector_id="DEL_ONORTH_BAWANA",
        name="Bawana",
        district="Outer North Delhi",
        lat=28.7967,
        lng=77.0371,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11267"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=1.8,
        primary_choke_corridor="Bawana Industrial Main Road",
        baseline_bus_capacity=28,
        primary_corridor_name="Bawana Industrial Access Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_ONORTH_NARELA",
        recommended_bypass_route="Kanjhawala Road Rural Bypass",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=280.0,
        is_industrial_zone=True,
        industrial_zone_type="Manufacturing & Chemical Industrial Complex",
    ),
    SectorConfig(
        sector_id="DEL_ONORTH_ALIPUR",
        name="Alipur",
        district="Outer North Delhi",
        lat=28.7970,
        lng=77.1360,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11266"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.4,
        primary_choke_corridor="Alipur GT Karnal Road Junction",
        baseline_bus_capacity=30,
        primary_corridor_name="GT Karnal Highway (NH-44)",
        free_flow_speed_kmh=65.0,
        upstream_sector_id="DEL_CNORTH_MT",
        recommended_bypass_route="Bakoli Village Feeder Bypass",
        discom_provider="Tata Power Delhi Distribution Limited (TPDDL)",
        rated_substation_capacity_mw=190.0,
        is_industrial_zone=False,
        industrial_zone_type="Highway Logistics & Agricultural Transit",
    ),

    # ── South Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SOUTH_SAKET",
        name="Saket",
        district="South Delhi",
        lat=28.5245,
        lng=77.2066,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.0,
        primary_choke_corridor="Saket Press Enclave Road",
        baseline_bus_capacity=40,
        primary_corridor_name="Press Enclave Road Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_SOUTH_HK",
        recommended_bypass_route="Mehrauli-Badarpur Road via Lado Sarai Loop",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=210.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial Mall & District Centre",
    ),
    SectorConfig(
        sector_id="DEL_SOUTH_HK",
        name="Hauz Khas",
        district="South Delhi",
        lat=28.5494,
        lng=77.2001,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=True,
        underpass_name="AIIMS Underpass & Flyover Junction",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="AIIMS & Hauz Khas Ring Road Junction",
        baseline_bus_capacity=65,
        primary_corridor_name="Sri Aurobindo Marg & Inner Ring Road",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_SOUTH_VK",
        recommended_bypass_route="August Kranti Marg via Asian Games Village Circuit",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=250.0,
        is_industrial_zone=False,
        industrial_zone_type="Institutional & Commercial Zone",
    ),
    SectorConfig(
        sector_id="DEL_SOUTH_VK",
        name="Vasant Kunj",
        district="South Delhi",
        lat=28.5200,
        lng=77.1590,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.1,
        primary_choke_corridor="Vasant Kunj Nelson Mandela Marg",
        baseline_bus_capacity=35,
        primary_corridor_name="Nelson Mandela Marg Expressway",
        free_flow_speed_kmh=60.0,
        upstream_sector_id="DEL_SWEST_MHP",
        recommended_bypass_route="Aruna Asaf Ali Marg via JNU Campus Link",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=200.0,
        is_industrial_zone=False,
        industrial_zone_type="Residential & Institutional Hub",
    ),

    # ── South East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SEAST_NP",
        name="Nehru Place",
        district="South East Delhi",
        lat=28.5492,
        lng=77.2517,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10112"},
        has_underpass=True,
        underpass_name="Kalkaji / Nehru Place Flyover Underpass",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=24.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=3.1,
        primary_choke_corridor="Nehru Place Outer Ring Road Terminal",
        baseline_bus_capacity=60,
        primary_corridor_name="Nehru Place Flyover Outer Ring Road",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_SEAST_GK",
        recommended_bypass_route="Lala Lajpat Rai Road via Zamrudpur Service Lane",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=230.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial IT & Financial Complex",
    ),
    SectorConfig(
        sector_id="DEL_SEAST_OKHLA",
        name="Okhla",
        district="South East Delhi",
        lat=28.5355,
        lng=77.2750,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10116"},
        has_underpass=True,
        underpass_name="Pul Prahladpur Railway Underpass",
        primary_drain_outfall="Agra Canal Outfall",
        baseline_drain_capacity_mmhr=15.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.7,
        primary_choke_corridor="Okhla Estate Road Junction",
        baseline_bus_capacity=35,
        primary_corridor_name="Maa Anandamayee Marg",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_SEAST_NP",
        recommended_bypass_route="Mathura Road via Crown Plaza Bypass",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=290.0,
        is_industrial_zone=True,
        industrial_zone_type="Okhla Industrial Estate Phase I-III",
    ),
    SectorConfig(
        sector_id="DEL_SEAST_GK",
        name="Kalkaji / Greater Kailash",
        district="South East Delhi",
        lat=28.5422,
        lng=77.2372,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10112"},
        has_underpass=True,
        underpass_name="Moolchand Underpass",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.1,
        primary_choke_corridor="Moolchand Underpass Flyover Corridor",
        baseline_bus_capacity=50,
        primary_corridor_name="Outer Ring Road (Chirag Delhi to Savitri Junction)",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_SOUTH_HK",
        recommended_bypass_route="August Kranti Marg via Asian Games Village Circuit",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=200.0,
        is_industrial_zone=False,
        industrial_zone_type="High-Density Residential & Commercial",
    ),

    # ── South West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SWEST_DWARKA",
        name="Dwarka",
        district="South West Delhi",
        lat=28.5921,
        lng=77.0460,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=True,
        underpass_name="Dwarka Sector 21 Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.4,
        primary_choke_corridor="Dwarka Sector 21 Transit Hub",
        baseline_bus_capacity=45,
        primary_corridor_name="Dwarka Expressway Link Corridor",
        free_flow_speed_kmh=60.0,
        upstream_sector_id="DEL_SWEST_NJF",
        recommended_bypass_route="Urban Extension Road II (UER-II) Bypass",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=260.0,
        is_industrial_zone=False,
        industrial_zone_type="Suburban Planned Residential Township",
    ),
    SectorConfig(
        sector_id="DEL_SWEST_NJF",
        name="Najafgarh",
        district="South West Delhi",
        lat=28.6090,
        lng=76.9800,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10120"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.3,
        primary_choke_corridor="Najafgarh Main Bus Stand Crossing",
        baseline_bus_capacity=38,
        primary_corridor_name="Najafgarh-Phirni Road Arterial",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_NWEST_NGL",
        recommended_bypass_route="Chhawla Village Feeder Link",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=180.0,
        is_industrial_zone=False,
        industrial_zone_type="Semi-Urban Commercial & Transport Junction",
    ),
    SectorConfig(
        sector_id="DEL_SWEST_MHP",
        name="Mahipalpur",
        district="South West Delhi",
        lat=28.5480,
        lng=77.1208,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=True,
        underpass_name="Mahipalpur Aerocity Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.3,
        primary_choke_corridor="Mahipalpur NH-48 Airport Junction",
        baseline_bus_capacity=52,
        primary_corridor_name="NH-48 Delhi-Gurugram Airport Arterial",
        free_flow_speed_kmh=65.0,
        upstream_sector_id="DEL_SOUTH_VK",
        recommended_bypass_route="Aerocity Spine Road via Rangpuri Tunnel Loop",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=270.0,
        is_industrial_zone=False,
        industrial_zone_type="Airport Commercial & Hospitality Corridor",
    ),

    # ── West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_WEST_RG",
        name="Rajouri Garden",
        district="West Delhi",
        lat=28.6469,
        lng=77.1220,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2555"},
        has_underpass=True,
        underpass_name="Zakhira / Mayapuri Underpass Junction",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="Rajouri Garden Ring Road Flyover Junction",
        baseline_bus_capacity=48,
        primary_corridor_name="West Ring Road (Patel Road Interchange)",
        free_flow_speed_kmh=55.0,
        upstream_sector_id="DEL_WEST_TILAK",
        recommended_bypass_route="Mayapuri Industrial Area Service Circuit",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=210.0,
        is_industrial_zone=True,
        industrial_zone_type="Mayapuri Industrial Area",
    ),
    SectorConfig(
        sector_id="DEL_WEST_JP",
        name="Janakpuri",
        district="West Delhi",
        lat=28.6219,
        lng=77.0819,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.6,
        primary_choke_corridor="Janakpuri District Centre Bus Corridor",
        baseline_bus_capacity=42,
        primary_corridor_name="Pankha Road Corridor",
        free_flow_speed_kmh=50.0,
        upstream_sector_id="DEL_SWEST_DWARKA",
        recommended_bypass_route="Jail Road via Hari Nagar Outer Avenue",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=200.0,
        is_industrial_zone=False,
        industrial_zone_type="Commercial District Centre & Residential",
    ),
    SectorConfig(
        sector_id="DEL_WEST_TILAK",
        name="Tilak Nagar",
        district="West Delhi",
        lat=28.6366,
        lng=77.0963,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2555"},
        has_underpass=True,
        underpass_name="Tilak Nagar Metro Underpass & Flyover Junction",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.4,
        primary_choke_corridor="Tilak Nagar Najafgarh Road Corridor",
        baseline_bus_capacity=45,
        primary_corridor_name="Najafgarh Road Metro Corridor",
        free_flow_speed_kmh=45.0,
        upstream_sector_id="DEL_WEST_JP",
        recommended_bypass_route="Shivaji Marg via Subhash Nagar Ring Link",
        discom_provider="BSES Rajdhani Power Limited (BRPL)",
        rated_substation_capacity_mw=190.0,
        is_industrial_zone=False,
        industrial_zone_type="High-Density Commercial & Metro Corridor",
    ),
]

# Quick lookup dict by sector_id
SECTOR_BY_ID = {s.sector_id: s for s in ALL_SECTORS}