# config/sectors_registry.py
from typing import List
from config.sector_config import SectorConfig

ALL_SECTORS: List[SectorConfig] = [
    # ── Central Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_CENTRAL_CP",
        name="Connaught Place",
        district="Central Delhi",
        lat=28.6315,
        lng=77.2167,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},  # Mandir Marg
        has_underpass=True,
        underpass_name="Minto Bridge Railway Underpass",
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Outer Circle & Minto Road Junction",
        baseline_bus_capacity=55,
    ),
    SectorConfig(
        sector_id="DEL_CENTRAL_KB",
        name="Karol Bagh",
        district="Central Delhi",
        lat=28.6514,
        lng=77.1907,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.5,
        primary_choke_corridor="Ajmal Khan Road & Pusa Road Junction",
        baseline_bus_capacity=48,
    ),
    SectorConfig(
        sector_id="DEL_CENTRAL_DG",
        name="Daryaganj",
        district="Central Delhi",
        lat=28.6459,
        lng=77.2410,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10111"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="Netaji Subhash Marg & Daryaganj Crossing",
        baseline_bus_capacity=42,
    ),

    # ── Central North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_CNORTH_MT",
        name="Model Town",
        district="Central North Delhi",
        lat=28.7115,
        lng=77.1913,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=True,
        underpass_name="Azadpur Railway Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.4,
        primary_choke_corridor="Model Town GT Road Junction",
        baseline_bus_capacity=38,
    ),
    SectorConfig(
        sector_id="DEL_CNORTH_SB",
        name="Shalimar Bagh",
        district="Central North Delhi",
        lat=28.7132,
        lng=77.1569,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10114"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.2,
        primary_choke_corridor="Shalimar Bagh Ring Road Crossing",
        baseline_bus_capacity=35,
    ),
    SectorConfig(
        sector_id="DEL_CNORTH_AV",
        name="Ashok Vihar",
        district="Central North Delhi",
        lat=28.6950,
        lng=77.1750,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=True,
        underpass_name="Satyawati Flyover Underbridge",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.3,
        primary_choke_corridor="Ashok Vihar Major Arterial Road",
        baseline_bus_capacity=32,
    ),

    # ── East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_EAST_LN",
        name="Laxmi Nagar",
        district="East Delhi",
        lat=28.6304,
        lng=77.2777,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=True,
        underpass_name="Vikas Marg Underpass",
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.6,
        primary_choke_corridor="Vikas Marg Transit Corridor",
        baseline_bus_capacity=60,
    ),
    SectorConfig(
        sector_id="DEL_EAST_MV",
        name="Mayur Vihar",
        district="East Delhi",
        lat=28.6096,
        lng=77.2905,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.1,
        primary_choke_corridor="Mayur Vihar Phase 1 Bus Corridor",
        baseline_bus_capacity=40,
    ),
    SectorConfig(
        sector_id="DEL_EAST_PV",
        name="Preet Vihar",
        district="East Delhi",
        lat=28.6389,
        lng=77.2953,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10704"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.5,
        primary_choke_corridor="Preet Vihar Vikas Marg Junction",
        baseline_bus_capacity=36,
    ),

    # ── New Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NEW_LUTYENS",
        name="Parliament / Lutyens",
        district="New Delhi",
        lat=28.6170,
        lng=77.2090,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=35.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.8,
        primary_choke_corridor="Central Secretariat Bus Terminal",
        baseline_bus_capacity=50,
    ),
    SectorConfig(
        sector_id="DEL_NEW_CHANAKYA",
        name="Chanakyapuri",
        district="New Delhi",
        lat=28.5933,
        lng=77.1900,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2556"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=35.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.6,
        primary_choke_corridor="Shanti Path Diplomatic Enclave",
        baseline_bus_capacity=25,
    ),
    SectorConfig(
        sector_id="DEL_NEW_KHAN",
        name="Khan Market",
        district="New Delhi",
        lat=28.5992,
        lng=77.2265,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10111"},
        has_underpass=True,
        underpass_name="Golf Links / Subramaniam Bharti Marg Junction",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=1.8,
        primary_choke_corridor="Subramaniam Bharti Marg Junction",
        baseline_bus_capacity=30,
    ),

    # ── North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NORTH_CL",
        name="Civil Lines",
        district="North Delhi",
        lat=28.6775,
        lng=77.2214,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10121"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.0,
        primary_choke_corridor="Civil Lines Boulevard Road",
        baseline_bus_capacity=30,
    ),
    SectorConfig(
        sector_id="DEL_NORTH_MN",
        name="Mukherjee Nagar",
        district="North Delhi",
        lat=28.7050,
        lng=77.2100,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10115"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.1,
        primary_choke_corridor="Mukherjee Nagar Banda Bahadur Marg",
        baseline_bus_capacity=45,
    ),
    SectorConfig(
        sector_id="DEL_NORTH_KGATE",
        name="Kashmere Gate",
        district="North Delhi",
        lat=28.6665,
        lng=77.2290,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=True,
        underpass_name="ISBT Ring Road Boulevard Underpass",
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.7,
        primary_choke_corridor="ISBT Kashmere Gate Ring Road Corridor",
        baseline_bus_capacity=75,
    ),

    # ── North East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NEAST_YV",
        name="Yamuna Vihar",
        district="North East Delhi",
        lat=28.6950,
        lng=77.2820,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10121"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.7,
        primary_choke_corridor="Yamuna Vihar Wazirabad Road",
        baseline_bus_capacity=38,
    ),
    SectorConfig(
        sector_id="DEL_NEAST_DG",
        name="Dilshad Garden",
        district="North East Delhi",
        lat=28.6800,
        lng=77.3210,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10118"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.3,
        primary_choke_corridor="Dilshad Garden GT Road Junction",
        baseline_bus_capacity=35,
    ),
    SectorConfig(
        sector_id="DEL_NEAST_SLP",
        name="Seelampur",
        district="North East Delhi",
        lat=28.6710,
        lng=77.2680,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10118"},
        has_underpass=True,
        underpass_name="Seelampur GT Road Underpass",
        primary_drain_outfall="Shahdara Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.4,
        primary_choke_corridor="Seelampur GT Road Transit Corridor",
        baseline_bus_capacity=50,
    ),

    # ── North West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_NWEST_ROH",
        name="Rohini",
        district="North West Delhi",
        lat=28.7495,
        lng=77.0700,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11267"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.5,
        primary_choke_corridor="Rohini Sector 7 Outer Ring Road",
        baseline_bus_capacity=42,
    ),
    SectorConfig(
        sector_id="DEL_NWEST_NGL",
        name="Nangloi",
        district="North West Delhi",
        lat=28.6830,
        lng=77.0640,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10708"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.0,
        primary_choke_corridor="Nangloi Rohtak Road Junction",
        baseline_bus_capacity=48,
    ),
    SectorConfig(
        sector_id="DEL_NWEST_PTM",
        name="Pitampura",
        district="North West Delhi",
        lat=28.6980,
        lng=77.1310,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10114"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.6,
        primary_choke_corridor="Pitampura TV Tower Junction",
        baseline_bus_capacity=40,
    ),

    # ── Old Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_OLD_CHANDNI",
        name="Chandni Chowk",
        district="Old Delhi",
        lat=28.6506,
        lng=77.2303,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.9,
        primary_choke_corridor="Chandni Chowk Main Road",
        baseline_bus_capacity=28,
    ),
    SectorConfig(
        sector_id="DEL_OLD_SADAR",
        name="Sadar Bazar",
        district="Old Delhi",
        lat=28.6580,
        lng=77.2130,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Sadar Bazar Qutub Road Junction",
        baseline_bus_capacity=30,
    ),
    SectorConfig(
        sector_id="DEL_OLD_CHAWRI",
        name="Chawri Bazar",
        district="Old Delhi",
        lat=28.6480,
        lng=77.2260,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2554"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Yamuna Main Trunk",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.8,
        primary_choke_corridor="Chawri Bazar Chowk",
        baseline_bus_capacity=20,
    ),

    # ── Outer North Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_ONORTH_NARELA",
        name="Narela",
        district="Outer North Delhi",
        lat=28.8520,
        lng=77.0910,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10706"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.5,
        primary_choke_corridor="Narela Anaj Mandi Road",
        baseline_bus_capacity=25,
    ),
    SectorConfig(
        sector_id="DEL_ONORTH_BAWANA",
        name="Bawana",
        district="Outer North Delhi",
        lat=28.7967,
        lng=77.0371,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11267"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=1.8,
        primary_choke_corridor="Bawana Industrial Main Road",
        baseline_bus_capacity=28,
    ),
    SectorConfig(
        sector_id="DEL_ONORTH_ALIPUR",
        name="Alipur",
        district="Outer North Delhi",
        lat=28.7970,
        lng=77.1360,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@11266"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.4,
        primary_choke_corridor="Alipur GT Karnal Road Junction",
        baseline_bus_capacity=30,
    ),

    # ── South Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SOUTH_SAKET",
        name="Saket",
        district="South Delhi",
        lat=28.5245,
        lng=77.2066,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.0,
        primary_choke_corridor="Saket Press Enclave Road",
        baseline_bus_capacity=40,
    ),
    SectorConfig(
        sector_id="DEL_SOUTH_HK",
        name="Hauz Khas",
        district="South Delhi",
        lat=28.5494,
        lng=77.2001,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=True,
        underpass_name="AIIMS Underpass & Flyover Junction",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="AIIMS & Hauz Khas Ring Road Junction",
        baseline_bus_capacity=65,
    ),
    SectorConfig(
        sector_id="DEL_SOUTH_VK",
        name="Vasant Kunj",
        district="South Delhi",
        lat=28.5200,
        lng=77.1590,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10707"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=30.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.1,
        primary_choke_corridor="Vasant Kunj Nelson Mandela Marg",
        baseline_bus_capacity=35,
    ),

    # ── South East Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SEAST_NP",
        name="Nehru Place",
        district="South East Delhi",
        lat=28.5492,
        lng=77.2517,
        is_live_anchor=True,
        station_ids={"smog_dispersion": "@10112"},
        has_underpass=True,
        underpass_name="Kalkaji / Nehru Place Flyover Underpass",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=24.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=3.1,
        primary_choke_corridor="Nehru Place Outer Ring Road Terminal",
        baseline_bus_capacity=60,
    ),
    SectorConfig(
        sector_id="DEL_SEAST_OKHLA",
        name="Okhla",
        district="South East Delhi",
        lat=28.5355,
        lng=77.2750,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10116"},
        has_underpass=True,
        underpass_name="Pul Prahladpur Railway Underpass",
        primary_drain_outfall="Agra Canal Outfall",
        baseline_drain_capacity_mmhr=15.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.7,
        primary_choke_corridor="Okhla Estate Road Junction",
        baseline_bus_capacity=35,
    ),
    SectorConfig(
        sector_id="DEL_SEAST_GK",
        name="Kalkaji / Greater Kailash",
        district="South East Delhi",
        lat=28.5422,
        lng=77.2372,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10112"},
        has_underpass=True,
        underpass_name="Moolchand Underpass",
        primary_drain_outfall="Barapulla Drain",
        baseline_drain_capacity_mmhr=22.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.1,
        primary_choke_corridor="Moolchand Underpass Flyover Corridor",
        baseline_bus_capacity=50,
    ),

    # ── South West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_SWEST_DWARKA",
        name="Dwarka",
        district="South West Delhi",
        lat=28.5921,
        lng=77.0460,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=True,
        underpass_name="Dwarka Sector 21 Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=28.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.4,
        primary_choke_corridor="Dwarka Sector 21 Transit Hub",
        baseline_bus_capacity=45,
    ),
    SectorConfig(
        sector_id="DEL_SWEST_NJF",
        name="Najafgarh",
        district="South West Delhi",
        lat=28.6090,
        lng=76.9800,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10120"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=0.3,
        primary_choke_corridor="Najafgarh Main Bus Stand Crossing",
        baseline_bus_capacity=38,
    ),
    SectorConfig(
        sector_id="DEL_SWEST_MHP",
        name="Mahipalpur",
        district="South West Delhi",
        lat=28.5480,
        lng=77.1208,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=True,
        underpass_name="Mahipalpur Aerocity Underpass",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.3,
        primary_choke_corridor="Mahipalpur NH-48 Airport Junction",
        baseline_bus_capacity=52,
    ),

    # ── West Delhi ──────────────────────────────────
    SectorConfig(
        sector_id="DEL_WEST_RG",
        name="Rajouri Garden",
        district="West Delhi",
        lat=28.6469,
        lng=77.1220,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2555"},
        has_underpass=True,
        underpass_name="Zakhira / Mayapuri Underpass Junction",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=20.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.2,
        primary_choke_corridor="Rajouri Garden Ring Road Flyover Junction",
        baseline_bus_capacity=48,
    ),
    SectorConfig(
        sector_id="DEL_WEST_JP",
        name="Janakpuri",
        district="West Delhi",
        lat=28.6219,
        lng=77.0819,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@10119"},
        has_underpass=False,
        underpass_name=None,
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=25.0,
        is_concrete_dense=False,
        uhi_baseline_offset_c=1.6,
        primary_choke_corridor="Janakpuri District Centre Bus Corridor",
        baseline_bus_capacity=42,
    ),
    SectorConfig(
        sector_id="DEL_WEST_TILAK",
        name="Tilak Nagar",
        district="West Delhi",
        lat=28.6366,
        lng=77.0963,
        is_live_anchor=False,
        station_ids={"smog_dispersion": "@2555"},
        has_underpass=True,
        underpass_name="Tilak Nagar Metro Underpass & Flyover Junction",
        primary_drain_outfall="Najafgarh Drain",
        baseline_drain_capacity_mmhr=18.0,
        is_concrete_dense=True,
        uhi_baseline_offset_c=2.4,
        primary_choke_corridor="Tilak Nagar Najafgarh Road Corridor",
        baseline_bus_capacity=45,
    ),
]

# Quick lookup dict by sector_id
SECTOR_BY_ID = {s.sector_id: s for s in ALL_SECTORS}